# Generated by Django 5.2.1 on 2025-05-30 09:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="RU",
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "case",
                    models.CharField(
                        choices=[
                            ("1", "Банкротство"),
                            ("2", "Cемейные споры"),
                            ("3", "Проблемы с ГИБДД"),
                            ("4", "Судебные приставы"),
                        ],
                        default="1",
                        max_length=20,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("M", "Москва"),
                            ("MO", "Московская область"),
                            ("K", "Краснодар"),
                        ],
                        default="M",
                        max_length=2,
                        verbose_name="Регион",
                    ),
                ),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            ("CALL", "Заявка на консультацию"),
                            ("MEET", "Запись на приём"),
                        ],
                        default="CALL",
                        max_length=4,
                        verbose_name="Тип заявки",
                    ),
                ),
            ],
        ),
    ]
