# Generated by Django 5.2.1 on 2025-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="message",
            field=models.TextField(
                default="Поьзователь не оставил сообщения",
                null=True,
                verbose_name="Сообщение",
            ),
        ),
    ]
