# Generated by Django 5.2.1 on 2025-05-30 12:28

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_request_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="RU", verbose_name="Номер телефона"
            ),
        ),
    ]
