# Generated by Django 5.2.1 on 2025-06-02 12:11

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_request_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Имя")),
                (
                    "case",
                    models.CharField(
                        choices=[
                            ("1", "Банкротство"),
                            ("2", "Cемейные споры"),
                            ("3", "Проблемы с ГИБДД"),
                            ("4", "Судебные приставы"),
                        ],
                        default="3",
                        max_length=20,
                        verbose_name="Направление",
                    ),
                ),
                ("text", models.TextField(verbose_name="Отзыв")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Модерация"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="request",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="message",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Сообщение"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                error_messages={"invalid": "Введите телефон в формате 89165556677."},
                max_length=128,
                region="RU",
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="region",
            field=models.CharField(
                choices=[
                    ("M", "Москва"),
                    ("MO", "Московская область"),
                    ("K", "Калининград"),
                ],
                default="M",
                max_length=2,
                verbose_name="Регион",
            ),
        ),
    ]
