# Generated by Django 5.2.1 on 2025-06-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_review_request_created_at_alter_request_message_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="request",
            options={"verbose_name": "Запрос", "verbose_name_plural": "Запросы"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AddField(
            model_name="request",
            name="comment",
            field=models.TextField(default="", verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="request",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="Заявка обработана"),
        ),
    ]
